### ISSUE TITLE
Convert to GitHub Actions

### ISSUE THREAD

**Issue by esarver** [tektronix/vscode-tsplang#71]
Convert the current Travis CI config to GitHub Actions.

**Comment by ethall** [comment]
The trigger rules ought to be set up for
1. `master` -- push, pull request
2. `dev` -- push, pull request
3. every other branch -- push
3. on tag

If we hit API limits, then we can re-evaluate.

**Comment by ethall** [comment]
Tests ought to include
- formatting
- unit tests + coverage
- upload results to Codecov
Bonus points for limiting this step to the `master` and `dev` branches.

**Comment by esarver** [comment]
Do you have any particular type of machine in mind? (Linux, Windows, Mac)?

**Comment by ethall** [comment]
All 3 for every trigger.  Probably overkill, but we can limit the scope as if it becomes necessary

**Comment by esarver** [comment]
Should there also be a step for `master` to deploy the package?

**Comment by ethall** [comment]
Yes, but it can be a placeholder step.
